home_page: 
  hk: "https://www.trivago.hk/en-HK/lm"
  # https://www.trivago.hk/en-HK/srl/hotels-tokyo-japan?search=105-1320;200-71462;dr-20240519-20240522;rc-1-2-4-6
  template: 
    url: "https://www.trivago.hk/en-HK/srl/hotels-{city_country}?search="
    param: "{star};{code};dr-{checkin}-{checkout};rc-{rooms}-{adults}{child_ages}"
    default:
      city_country: tokyo-japan
      code: 200-71462
      rooms: 1
      adults: 2
      child_ages: ""

language: English

loading_wait_time: 3

searchlist: 
  name: searchlist.xlsx
  path: res\

logging_dir: log\
logging_path: config\logging.yml

output:
  path: output\
  titles:
    - Page_No
    - City
    - Hotelname
    - Recommend booking
    - Price
    - Star
    - Type
    - Other1 booking
    - Other1 price
    - Lowest booking
    - Lowest price
    - Checkin
    - Checkout
    - Currency

stars:
  3: 105-1318
  4: 105-1320
  5: 105-1322

selectors:
  Hotelname: './/*[@data-testid="details-section"]//*[@data-testid="item-name"]//span'
  Star: './/*[@data-testid="star-rating"]//meta'
  Type: './/*[@data-testid="accommodation-type"]'
  Recommend booking: './/*[@data-testid="recommended-price-partner"]'
  Price: './/*[@data-testid="clickout-area"]//*[@data-testid="recommended-price"]'
  Other1 booking: './/*[contains(@data-testid,"alternative-deal")]//*[@itemprop="name"]'
  Other1 price: './/*[contains(@data-testid,"alternative-deal")]//*[@itemprop="price"]'
  Lowest booking: './/*[@data-testid="cheapest-price-label"]/span/span[3]'
  Lowest price: './/*[@data-testid="cheapest-price-label"]//*[@itemprop="price"]'

edge_options:
  arguments:
    - --ignore-certificate-errors
    - --ignore-ssl-errors
    - --accept-language=en
    - --disable-extensions
    - --disable-popup-blocking
    - --incognito
    - --start-maximized
    - --user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
  prefs:
    first_run_customized: False
    first_run: False
    welcome_page_on_startup_enabled: False
    welcome_page_enabled: False

chrome_options:
  arguments:
    - --ignore-certificate-errors
    - --ignore-ssl-errors
    - --accept-language=en
    - --disable-extensions
    - --disable-popup-blocking
    - --incognito
    - --start-maximized
    - --user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
  prefs:
    profile.default_content_setting_values.notifications: 2
    credentials_enable_service: False
    profile.password_manager_enabled: False
    browser: 
      first_run_tabs: []
    first_run_customized: False
    first_run: False
    welcome_page_on_startup_enabled: False
    welcome_page_enabled: False

db:
  path: res\trivago.db
  tables:
    city:
      create: |
        CREATE TABLE IF NOT EXISTS city (
            search_key TEXT UNIQUE,
            city_country TEXT,
            code TEXT,
            add_time TEXT
        )
      insert: |
        INSERT INTO city (search_key, city_country, code, add_time)
        VALUES (?, ?, ?, ?)
      delete: |
        DELETE FROM city
        WHERE search_key = ?;
      update_search_key: |
        UPDATE city
        SET search_key = ?
        WHERE search_key = ?;
      update: |
        UPDATE city
        SET city_country = ?, 
            code = ?, 
            add_time = ?
        WHERE search_key = ?;
      search: |
        SELECT city_country, code FROM city
        WHERE search_key = ?;

currency_dict:
  USD: US$
  HKD: $
        




