home_page: 
  hk: "https://www.trivago.hk/en-HK/lm"
  # https://www.trivago.hk/en-HK/srl/hotels-tokyo-japan?search=200-71462;dr-20240519-20240522;rc-1-2-4-6
  template: 
    url: "https://www.trivago.hk/en-HK/srl/hotels-{city}-{country}?search="
    param: "{addressid};dr-{checkin}-{checkout};rc-{rooms}-{Adults}{child_ages}"
    default:
      city: tokyo
      countrym: japan
      addressid: 200-71462
bot_check: ""
search_item:
  where_to: ""
  checkin: ""
  checkout: ""
  guestandrooms: ""
language: English
currency: HKD
advertise: 
  dialog:
    data-testid: "modal-container"
    closeButton:
      class: IdleNotification_closeButton__Hlj6a

searchlist: 
  name: searchlist.xlsx
  path: trivago_scraping\res\

logging_path: trivago_scraping\config\logging.yml

output: trivago_scraping\output

db:
  path: trivago_scraping\res\trivago.db
  tables:
    city:
      create: |
        CREATE TABLE IF NOT EXISTS city (
            No INTEGER PRIMARY KEY AUTOINCREMENT,
            search_key TEXT,
            city_name TEXT,
            country TEXT,
            code TEXT,
            add_time TEXT
        )
      insert: |
        INSERT INTO city (search_key, city_name, country, code, add_time)
        VALUES (?, ?, ?, ?, ?)
        



